name: sim_card_info
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.wsc.sim_card_info
        pluginClass: SimCardInfoPlugin
      ios:
        pluginClass: SimCardInfoPlugin
      linux:
        pluginClass: SimCardInfoPlugin
      macos:
        pluginClass: SimCardInfoPlugin
      windows:
        pluginClass: SimCardInfoPluginCApi
      web:
        pluginClass: SimCardInfoWeb
        fileName: sim_card_info_web.dart
